name: cypress_run
on: workflow_dispatch
jobs:
    cyp-run:
        runs-on: ubuntu-latest
        steps:
            - name: code the code
              uses: actions/checkout@v4 
            - name: deps
              run: npm ci 
            - name: cyp run
              uses: cypress-io/github-action@v6
